mysql:
  username: ${MYSQL_USERNAME:root}
  password: ${MYSQL_PASSWORD:123456}
  schema: adm_videos
  url: ${MYSQL_URL:localhost:3306}

keycloak:
  realm: ${KEYCLOAK_REALM:codeflix}
  host: ${KEYCLOAK_HOST:http://localhost:8888}

server:
  undertow:
    threads:
      worker: 64 # Generally this should be reasonably high, at least 10 per CPU core: https://undertow.io/undertow-docs/undertow-docs-2.1.0/index.html#listeners-2
      io: 4 # One IO thread per CPU core is a reasonable default: https://undertow.io/undertow-docs/undertow-docs-2.1.0/index.html#listeners-2