version: '3.7'

services:
  app:
    container_name: adm_videos_app
    build: .
    #image: ioliveira1/admin-catalogo:main-3 # Executa docker compose com a imagem criada pelo ci-cd
    profiles: ["app"]
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - adm_videos_network

  mysql:
    container_name: adm_videos_mysql
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=adm_videos
    security_opt:
      - seccomp:unconfined
    ports:
      - "3306:3306"
    networks:
      - adm_videos_network

  keycloak:
    container_name: adm_videos_keycloak
    image: quay.io/keycloak/keycloak:22.0.5
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - "8090:8080"
    command:
      - start-dev
    networks:
      - adm_videos_network


networks:
  adm_videos_network: