version: '3.7'

services:
  mysql:
    container_name: adm_videos_mysql
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: adm_videos
      MYSQL_ROOT_HOST: '%' # Permite root connections (localhost, mysql, etc.) de outros hosts e não somente de dentro do container https://dev.mysql.com/doc/refman/8.0/en/docker-mysql-more-topics.html#docker_var_mysql-root-host
    security_opt:
      - seccomp:unconfined
    volumes:
      - ../.docker/mysql:/var/lib/mysql:rw
    ports:
      - "3306:3306"
    networks:
      - adm_videos_services

  keycloak:
    container_name: adm_videos_keycloak
    image: quay.io/keycloak/keycloak:22.0.5
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - "8888:8888"
    #command: ["start-dev", "--http-port=8888"] # Utilizar quando a aplicação for executada fora do Docker
    command: ["start-dev", "--http-port=8888", "--hostname-url=http://keycloak:8888"] # Utilizar quando a aplicação for executada pelo docker compose
    volumes:
      - ../.docker/keycloak:/opt/keycloak/data/h2:rw
    networks:
      - adm_videos_services

networks:
  adm_videos_services:
    external: true