version: '3.7'

services:
  app:
    container_name: adm_videos_app
    #image: ioliveira1/admin-catalogo:main-'NR_VERSION' # Executa docker compose com a imagem criada pelo ci-cd
    build:
      context: ../../
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8080:8080"
    networks:
      - adm_videos_network
      - adm_videos_services

networks:
  adm_videos_network:
  adm_videos_services:
    external: true