name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - master
      - develop
      - 'feature/**'
      - 'bugfix/**'
  workflow_dispatch: #Habilita a execução manual através da interface do Github Actions

# Envio para Dockerhub
env:
  IMAGE_NAME: ioliveira1/admin-catalogo

jobs:
  # Job para execução dos testes
  tests:
    name: Tests runner
    runs-on: ubuntu-latest
    # Configuração dos passos do job
    steps:
      # 1. Checkout do código fonte
      - uses: actions/checkout@v3
      # 2. Configurar o JDK na máquina
      - name: Set up JDK@17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      # 3. Executar os testes da aplicação
      - name: Run application tests
        run: ./gradlew test

  # Job para build da aplicação
  build:
    name: Build runner
    needs: tests # Para fazer o build, precisa ter passado pelos testes ('tests' = nome do job acima)
    runs-on: ubuntu-latest
    # Configuração dos passos do job
    steps:
      # 1. Checkout do código fonte
      - uses: actions/checkout@v3
      # 2. Configurar o JDK na máquina
      - name: Set up JDK@17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      # 3. Valida a existência do Gradle Wrapper
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      # 4. Realiza o build para gerar o artefato final
      - name: Build application
        uses: gradle/gradle-build-action@v2 # Poderia também ser executado sem uma action, por exemplo ./gradlew build
        with:
          arguments: clean build -x test
      # 5. Definir a variável branch name
      - name: Set BUILD_TAG
        run: |
          echo BUILD_TAG=$(echo ${{ github.head_ref || github.ref_name }} | sed "s,/,_,g")-${{ github.run_number }} >> $GITHUB_ENV
      # 6. Print BUILD_TAG
      - name: Print BUILD_TAG defined
        run: |
          echo "Branch     ---> ${{ github.head_ref || github.ref_name }}"
          echo "Run number ---> ${{ github.run_number }}"
          echo "Tag        ---> ${{ env.BUILD_TAG }}"
      # 7. Log in to DockerHub
      - name: Log in DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      # 8. Build & Deploy da imagem
      - name: Build & push da imagem do docker
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          build-args: VERSION=${{ env.BUILD_TAG }}
          tags: ${{ env.IMAGE_NAME }}:${{ env.BUILD_TAG }}